# Generated by Django 5.2.6 on 2025-09-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_category_user'),
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Channel',
        ),
        migrations.AlterField(
            model_name='channelgroup',
            name='channels',
            field=models.ManyToManyField(related_name='groups', to='index.channel'),
        ),
    ]
