# Generated by Django 5.2.6 on 2025-09-18 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_channelgroup_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
        migrations.RemoveField(
            model_name='channelgroup',
            name='user',
        ),
        migrations.AddField(
            model_name='category',
            name='userconfig',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owned_categories', to='account.userchannelconfig'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='channelgroup',
            name='userconfig',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='channel_groups', to='account.userchannelconfig'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userchannelconfig',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='configs_for_users', to='account.category'),
        ),
    ]
