# Generated by Django 5.2.6 on 2025-09-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_category_user_remove_channelgroup_user_and_more'),
        ('index', '0002_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchannelconfig',
            name='viewed_videos',
            field=models.ManyToManyField(blank=True, related_name='viewed_by_users', to='index.video'),
        ),
    ]
