# Generated by Django 5.2.6 on 2025-09-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(max_length=255, unique=True)),
                ('youtube_id', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
